version: "1.0"
stages:
  - clone
  - test
steps:
  main_clone:
    type: git-clone
    stage: clone
    description: Cloning ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}@${{CF_BRANCH}}
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    revision: ${{CF_BRANCH}}
  GoBuildVetAndTest:
    title: Running go vet and go test, uploading coverage to Codacy
    stage: test
    image: golang:1.15
    commands:
      - export GOPROXY=${{GO_PROXY}}
      - export GONOSUMDB="github.com/gymshark"
      - go vet ./...
      - go test --coverprofile cover.out ./...
      - go get -u github.com/schrej/godacov
      - godacov -t ${{CODACY_API_KEY}} -r cover.out -c ${{CF_REVISION}}
